#!/usr/bin/env python
# coding: utf-8

# In[2]:


import os


# In[3]:


os.listdir()


# In[4]:


import pandas as pd
import numpy as np


# In[5]:


df = pd.read_csv('winequality-red.csv')


# In[6]:


df.head(2)


# In[7]:


df.head()


# In[8]:


df.tail()


# In[9]:


df.sample(5)


# In[10]:


df.describe()


# In[11]:


df.info()


# In[12]:


df.shape


# In[13]:


df.size


# In[14]:


df.columns


# In[15]:


df.columns.tolist()


# In[16]:


df.head()


# In[17]:


df.loc[1]


# In[18]:


df.loc[1:3]


# In[19]:


df.loc[1,'fixed acidity']


# In[20]:


df.loc[3,'chlorides']


# In[21]:


df.loc[4,'alcohol']


# In[25]:


df.loc[0:1, ['chlorides', 'density']]


# In[27]:


df.loc[2:3, ['residual sugar','pH']]


# In[ ]:





# In[ ]:





# In[ ]:





# In[ ]:





# In[ ]:




